# Make a newly connected audio device the default and move active playback to it.
# module-switch-on-connect ignores HDMI devices by default.
pulse.cmd = [
    { cmd = "load-module" args = "module-switch-on-connect" flags = [ ] }
]
